version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14.5.0'
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: npm i
      - run: npm i react react-dom
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          no_output_timeout: 60m
          command: npm run test -- --maxWorkers=4

  test-and-release:
    executor:
      name: node/default
      tag: '14.5.0'
    resource_class: xlarge
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm i react react-dom
            - run:
                name: Run Tests
                no_output_timeout: 60m
                command: npm run test -- --maxWorkers=4
            - run: npx semantic-release
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
  test-and-release:
    jobs:
      - test-and-release:
          filters:
            branches:
              only: master
